# NUMPY TUTORALS

In [25]:
import numpy as np

In [26]:
A = np.array([[1,2],[4,5]])
A

array([[1, 2],
       [4, 5]])

In [27]:
B = np.array([1,2])

In [28]:
x = np.linalg.solve(A,B)
x

array([-0.33333333,  0.66666667])

In [29]:
A = np.array([[1,1],[1.5,4]])
B = np.array([2200,5000])
x = np.linalg.solve(A,B)
x

array([1520.,  680.])